### PR TITLE
feat: start selection automatically and add option to disable it

### PR DESCRIPTION
**Pull request by cristiansofronie**
Make it so that by default you begin selection and also add option to disable that

### CODE REVIEW

**Comment by IngoMeyer441** [comment]
Cool feature! The code looks good to me, and it is very nice that you share your changes.

I have only one change request: Could you set the default for the auto selection to off? Otherwise, the plugin behavior will change for all users on the next update.

**Comment by cristiansofronie** [comment]
I turned it of by default and updated the readme also

**Comment by IngoMeyer441** [comment]
Thank you very much!

**Comment by IngoMeyer441** [comment]
I rebased your commits on `develop` and merged it into `master` afterward (on the command line). It seems that GitHub does not detect automatically, that this PR is merged now, so I close it by hand.

**Pull request closed without merging**
