### PR TITLE
Let bindings differ by key table.

### PR DESCRIPTION
**Pull request by butwerenotthereyet**
The root and copy key tables are different and they have different entries.  There might not be a good binding that can be used in both modes.  Space, for example, begins selection in copy-mode.  Let each different key table have a different binding (or no binding at all) to start easymotion.

### CODE REVIEW

**Comment by IngoMeyer441** [comment]
It is a good idea to separate the bindings for copy and non-copy mode. I would use another name than `@easy-motion-root-prefix` because it could be confusing that it is named `root` but the key is bound on the `prefix` key table. What do you think about keeping `@easy-motion-prefix` for non-copy mode and to use this key as the default for `@easy-motion-copy-prefix`? We can avoid `root` in the name and people already using tmux-easy-motion don't need to change their tmux configuration.

**Comment by butwerenotthereyet** [comment]
Okay!  What do you think?

**Comment by IngoMeyer441** [comment]
Hey, thanks for the changes. I additionally changed `@easy-motion-copy` to `@easy-motion-copy-mode-prefix` and mentioned the new options in the README file. Please see my attached diff patch.

```diff
diff --git a/README.md b/README.md
index 52c01e4..20ef5bc 100644
--- a/README.md
+++ b/README.md
@@ -58,6 +58,8 @@ If you are using a quite recent Linux distribution or macOS, an appropriate Pyth
    bind-key -T copy-mode-vi v send-keys -X begin-selection
    ```
 
+   You can also configure another key binding for copy mode by setting `@easy-motion-copy-mode-prefix`.
+
 ### Manual
 
 1. Clone this repository and add
@@ -90,6 +92,13 @@ a small set of target keys was configured.
 
 ## Configuration
 
+### Key bindings
+
+You can set a prefix key for tmux-easy-motion with the `@easy-motion-prefix` option. It will be bound on the prefix and
+the copy-mode-vi key table. If you don't want to use the same prefix key for both modes, you can set another key binding
+for copy mode with the `@easy-motion-copy-mode-prefix` option or you can disable the key bindings by setting
+`@easy-motion-prefix-enabled` and/or `@easy-motion-copy-mode-prefix-enabled` to `0`.
+
 ### Target keys
 
 The target keys can be configured with the `@easy-motion-target-keys` option. The default is taken from the
diff --git a/easy_motion.tmux b/easy_motion.tmux
index 87ba057..0b13acb 100755
--- a/easy_motion.tmux
+++ b/easy_motion.tmux
@@ -27,10 +27,10 @@ setup_bindings() {
     server_pid="$1"
 
     if ((EASY_MOTION_PREFIX_ENABLED)); then
-        tmux bind-key "${EASY_MOTION_KEY}" switch-client -T easy-motion
+        tmux bind-key "${EASY_MOTION_PREFIX}" switch-client -T easy-motion
     fi
-    if ((EASY_MOTION_COPY_ENABLED)); then
-        tmux bind-key -T copy-mode-vi "${EASY_MOTION_COPY_KEY}" switch-client -T easy-motion
+    if ((EASY_MOTION_COPY_MODE_PREFIX_ENABLED)); then
+        tmux bind-key -T copy-mode-vi "${EASY_MOTION_COPY_MODE_PREFIX}" switch-client -T easy-motion
     fi
     while read -n1 key; do
         tmux bind-key -T easy-motion "${key}" run-shell -b "${SCRIPTS_DIR}/easy_motion.sh '${server_pid}' '#{session_id}' '#{window_id}' '#{pane_id}' '${key}'"
diff --git a/scripts/options.sh b/scripts/options.sh
index 2a56593..2e7043f 100644
--- a/scripts/options.sh
+++ b/scripts/options.sh
@@ -8,8 +8,8 @@ source "${SCRIPTS_DIR}/helpers.sh"
 
 
 EASY_MOTION_PREFIX_ENABLED_DEFAULT="1"
-EASY_MOTION_KEY_DEFAULT="Space"
-EASY_MOTION_COPY_ENABLED_DEFAULT="1"
+EASY_MOTION_PREFIX_DEFAULT="Space"
+EASY_MOTION_COPY_MODE_PREFIX_ENABLED_DEFAULT="1"
 EASY_MOTION_DIM_STYLE_DEFAULT="fg=colour242"
 EASY_MOTION_HIGHLIGHT_STYLE_DEFAULT="fg=colour196,bold"
 EASY_MOTION_HIGHLIGHT_2_FIRST_STYLE_DEFAULT="fg=brightyellow,bold"
@@ -17,9 +17,9 @@ EASY_MOTION_HIGHLIGHT_2_SECOND_STYLE_DEFAULT="fg=yellow,bold"
 EASY_MOTION_TARGET_KEYS_DEFAULT="asdghklqwertyuiopzxcvbnmfj;"
 
 EASY_MOTION_PREFIX_ENABLED_OPTION="@easy-motion-prefix-enabled"
-EASY_MOTION_KEY_OPTION="@easy-motion-prefix"
-EASY_MOTION_COPY_ENABLED_OPTION="@easy-motion-copy-enabled"
-EASY_MOTION_COPY_KEY_OPTION="@easy-motion-copy"
+EASY_MOTION_PREFIX_OPTION="@easy-motion-prefix"
+EASY_MOTION_COPY_MODE_PREFIX_ENABLED_OPTION="@easy-motion-copy-mode-prefix-enabled"
+EASY_MOTION_COPY_MODE_PREFIX_OPTION="@easy-motion-copy-mode-prefix"
 EASY_MOTION_DIM_STYLE_OPTION="@easy-motion-dim-style"
 EASY_MOTION_HIGHLIGHT_STYLE_OPTION="@easy-motion-highlight-style"
 EASY_MOTION_HIGHLIGHT_2_FIRST_STYLE_OPTION="@easy-motion-highlight-2-first-style"
@@ -29,9 +29,9 @@ EASY_MOTION_TARGET_KEYS_OPTION="@easy-motion-target-keys"
 
 read_options() {
     EASY_MOTION_PREFIX_ENABLED="$(get_tmux_option "${EASY_MOTION_PREFIX_ENABLED_OPTION}" "${EASY_MOTION_PREFIX_ENABLED_DEFAULT}")" && \
-    EASY_MOTION_KEY="$(get_tmux_option "${EASY_MOTION_KEY_OPTION}" "${EASY_MOTION_KEY_DEFAULT}")" && \
-    EASY_MOTION_COPY_ENABLED="$(get_tmux_option "${EASY_MOTION_COPY_ENABLED_OPTION}" "${EASY_MOTION_COPY_ENABLED_DEFAULT}")" && \
-    EASY_MOTION_COPY_KEY="$(get_tmux_option "${EASY_MOTION_COPY_KEY_OPTION}" "${EASY_MOTION_KEY}")" && \
+    EASY_MOTION_PREFIX="$(get_tmux_option "${EASY_MOTION_PREFIX_OPTION}" "${EASY_MOTION_PREFIX_DEFAULT}")" && \
+    EASY_MOTION_COPY_MODE_PREFIX_ENABLED="$(get_tmux_option "${EASY_MOTION_COPY_MODE_PREFIX_ENABLED_OPTION}" "${EASY_MOTION_COPY_MODE_PREFIX_ENABLED_DEFAULT}")" && \
+    EASY_MOTION_COPY_MODE_PREFIX="$(get_tmux_option "${EASY_MOTION_COPY_MODE_PREFIX_OPTION}" "${EASY_MOTION_PREFIX}")" && \
     EASY_MOTION_DIM_STYLE="$(get_tmux_option "${EASY_MOTION_DIM_STYLE_OPTION}" "${EASY_MOTION_DIM_STYLE_DEFAULT}")" && \
     EASY_MOTION_HIGHLIGHT_STYLE="$(get_tmux_option "${EASY_MOTION_HIGHLIGHT_STYLE_OPTION}" "${EASY_MOTION_HIGHLIGHT_STYLE_DEFAULT}")" && \
     EASY_MOTION_HIGHLIGHT_2_FIRST_STYLE="$(get_tmux_option "${EASY_MOTION_HIGHLIGHT_2_FIRST_STYLE_OPTION}" "${EASY_MOTION_HIGHLIGHT_2_FIRST_STYLE_DEFAULT}")" && \
```

**Comment by butwerenotthereyet** [comment]
I tried rebasing.

**Comment by IngoMeyer441** [comment]
Ah, sorry for all the rebasing work :see_no_evil:.
I found a small bug in `get_prefixed_enabled_for_key_table` (`return` instead of `echo`) and intending the code in `easy_motion.tmux` removed the tabs in the Bash here documents (tabs are stripped by Bash when reading a here doc with `-EOF` and so can be used for indenting a here doc). 
That is the final patch:
```diff
diff --git a/easy_motion.tmux b/easy_motion.tmux
index f07af42..d26e103 100755
--- a/easy_motion.tmux
+++ b/easy_motion.tmux
@@ -25,18 +25,18 @@ setup_bindings() {
         if (( EASY_MOTION_VERBOSE )); then
             if (( EASY_MOTION_PREFIX_ENABLED )); then
                 tmux source - <<-EOF
-                    bind-key "${EASY_MOTION_PREFIX}" {
-                        switch-client -T easy-motion
-                        display-message "tmux-easy-motion activated, please type a motion command."
-                    }
+					bind-key "${EASY_MOTION_PREFIX}" {
+					    switch-client -T easy-motion
+					    display-message "tmux-easy-motion activated, please type a motion command."
+					}
 				EOF
             fi
             if (( EASY_MOTION_COPY_MODE_PREFIX_ENABLED )); then
                 tmux source - <<-EOF
-                    bind-key -T copy-mode-vi "${EASY_MOTION_COPY_MODE_PREFIX}" {
-                        switch-client -T easy-motion
-                        display-message "tmux-easy-motion activated, please type a motion command."
-                    }
+					bind-key -T copy-mode-vi "${EASY_MOTION_COPY_MODE_PREFIX}" {
+					    switch-client -T easy-motion
+					    display-message "tmux-easy-motion activated, please type a motion command."
+					}
 				EOF
             fi
         else
diff --git a/scripts/helpers.sh b/scripts/helpers.sh
index 0efabd4..026c87a 100644
--- a/scripts/helpers.sh
+++ b/scripts/helpers.sh
@@ -8,10 +8,10 @@ source "${SCRIPTS_DIR}/common_variables.sh"
 get_prefix_enabled_for_key_table() {
     case "${key_table}" in
         "prefix")
-            return "${EASY_MOTION_PREFIX_ENABLED}"
+            echo "${EASY_MOTION_PREFIX_ENABLED}"
             ;;
         "copy-mode-vi")
-            return "${EASY_MOTION_COPY_MODE_PREFIX_ENABLED}"
+            echo "${EASY_MOTION_COPY_MODE_PREFIX_ENABLED}"
             ;;
     esac
 }
```
Thanks again!

**Comment by butwerenotthereyet** [comment]
Thanks for looking!  I fixed tabs, but I think `return` is right here.  I used this way.

```
if ! get_prefix_enabled_for_key_table "${key_table}"; then
    continue
fi
```

So returning the integer gets you what you want:

```
$ZERO=0
$ONE=1


$#using echo
$function is_a() { case $1 in a) echo "$ZERO"; ;; b) echo "$ONE" ;; esac }
$if ! is_a a; then echo no; fi
0
$if ! is_a b; then echo no; fi
1


$#using return
$function is_a() { case $1 in a) return "$ZERO"; ;; b) return "$ONE" ;; esac }
$if ! is_a a; then echo no; fi
$if ! is_a b; then echo no; fi
no
```

**Comment by IngoMeyer441** [comment]
Ah sorry, you are right, `return` is correct here. But the bool logic needs to be inverted since a `0` return value is interpreted as `true` in Bash:
```diff
diff --git a/scripts/helpers.sh b/scripts/helpers.sh
index 0efabd4..5941983 100644
--- a/scripts/helpers.sh
+++ b/scripts/helpers.sh
@@ -8,10 +8,10 @@ source "${SCRIPTS_DIR}/common_variables.sh"
 get_prefix_enabled_for_key_table() {
     case "${key_table}" in
         "prefix")
-            return "${EASY_MOTION_PREFIX_ENABLED}"
+            return $(( ! EASY_MOTION_PREFIX_ENABLED ))
             ;;
         "copy-mode-vi")
-            return "${EASY_MOTION_COPY_MODE_PREFIX_ENABLED}"
+            return $(( ! EASY_MOTION_COPY_MODE_PREFIX_ENABLED ))
             ;;
     esac
 }
```

**Comment by butwerenotthereyet** [comment]
Fixed!

**Pull request merged**
